---
apiVersion: v1
kind: Service
metadata:
  name: jupyterhub
  labels:
    app: jupyterhub
spec:
  #type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: jupyterhub
---
apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-api
  labels:
    app: jupyterhub-api
spec:
  #type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8001
  selector:
    app: jupyterhub
