---
apiVersion: v1
kind: ReplicationController
metadata:
  name: jupyterhub
  labels:
    name: jupyterhub
spec:
  replicas: 1
  selector:
    app: jupyterhub
  template:
    metadata:
      labels:
        app: jupyterhub
    spec:
      imagePullSecrets:
        - name: sidregistrykey
      containers:
        - name: jupyterhub-proxy
          image: jupyterhub/configurable-http-proxy
          ports:
            - containerPort: 8000
              name: jhubproxyport
            - containerPort: 8001
              name: jhubapiport
          command:
            - configurable-http-proxy
            - --ip
            - 0.0.0.0
            - --api-ip
            - 0.0.0.0
            - --default-target
            - http://127.0.0.1:8081
            - --error-target
            - http://127.0.0.1:8081/hub/error
        - name: jupyterhub
          image: docker-registry.atos.local:5000/jupyterhub:latest
          ports:
            - containerPort: 8081
              name: jhubport
          volumeMounts:
            - name: token
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              readOnly: true
            - name: jupyterhub-db
              mountPath: /srv/jupyterhub/db
            - name: jupyterhub-notebooks
              mountPath: /srv/jupyterhub/notebooks
            - name: jupyterhub-certs
              mountPath: /srv/jupyterhub/ssl
      volumes:
        - name: token
          secret:
            secretName: "default-token-brjs3"
        - name: jupyterhub-db
          hostPath:
            path: "/data/jupyterhub/db"
        - name: jupyterhub-notebooks
          hostPath:
            path: "/data/jupyterhub/notebooks"
        - name: jupyterhub-certs
          hostPath:
            path: "/data/jupyterhub/certs"
